language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
install:
- npm install
script:
- npm run test_coverage
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: dU28jeJmObI40+tV0TZHOXHTxoroTsi5aLi3SUZDSB3ImV7o4sZGbBhIQXTmqV0OZQiyJK0QDCrVVR1YFJpmCCMzqocbGWGY/EXmOM+fQ6ZsR3ZvcTy380mIR7Igp+TaCnS5dQPWNN3rRDrZirddSJ7i5UeBDv/O1MQro8Dduwg3KWUF7Zvk8bhKtKi7Zqen7xig5OJJsgUEFPHlSHOFIRHvZNlcHpsxfyEA8iLEl69aUo0QdYY1/n0J9uQlYxLxrdun7F2UguJkY9jVWkKT3S9LwKXRp0GcDG5xobX2aRv3qPZymho4pC5LlKejlIMUPlltGh8GqLuMmjUQMlLZFineYEKbdue88oAOcVTAFNQm653wIgHGB05XFv6qv6LkNeUNBiZqKeaCuMMS8YkbrP7JBTKp1XvHmzxj444TgDUf2Tgf9b9MuSW4Sfp4Acv9yT51f+Mr6Yst23OCro66x71ycm6jLh7OWZoy0mZmmcVX6EZM15BI0GVKkOKk8f9bvQiB5hanEXX+vtFKuCn+gAzOTZt2VUl3nwyLSwtMIqQKAcIuS6oFuUsiFsR2sPQdtectDBRSyacxgqec7astNhftd2g5UzBSWQtTTlB2F7Cz6tUEECcZmIfsniiag/o6stfu0EngEIE6mQpX3WUWaX/AMfTOML2AFjYhSrSyzYo=
  on:
    tags: true
    repo: nlibjs/human-readable
notifications:
  slack:
    secure: lTgRdAROkxrtkJTM8zBd+UVyMlzXXv2jGmUjprwtoAcW9b32+Uaz01K628l2ppkgqHs7lETzsfZFIb/w0eJNmTii66suchUV76r8nDw4jAa6NK8HN4Oa97TTRykesnv+BpyzNeYdesLq50QWJO8s3ui/Gz6TUhj3JNNb1sWrCZE7JQ3s0ZaaGAoXX772q/VOQ2PF2VgNY8beL6//mAcT4Uxj/70eNflgwmiDkMTeak90aKFApUzeliydC9s5jQC6ltJSYswoFOvmKfVeaGFSSxwS6OANyqlJvJs5HBzCD2U40Ro2NFO/jMDFLgW7CE/Z8UmnnmANP0NRJwwRba7FxRzUoUOiJ7DSYpYcxAEds05I4Aml8G440o0iIXD7I2VubmL6PiSx/XG/BrgTK4WlEOH+0JWjdjUy8vpyvWE05HmcWxj1eb/KxsBB0GTPKw+A4BRRgWKRdxdFSH0IdslKoTxABhHQ3hdq7ouSj53IpGxuYwAodH99lfmNHJT2m0f3eHbAuKPAtd+1kagX37zUIhCAJDoMR5Ru5pxBiXq2vtqND1habLyJ3fnMEWBt3i1iA0ulGXJXDja6g30HdTca15aI261ruIOZLP41+FV8H90XcO4m0I9pVqUmCpZySG4GYGpiGv1OCIPGztcYQGH7uR29HoJSqWEUb45FIaoPKDA=
